### ISSUE TITLE
camelToKebab function should do nothing if argument is in kebab case

### ISSUE THREAD

**Issue by mfpjayb** [monster-js/monster-js#8]
### Which @monster-js/* package(s) are the source of the bug?

cli, core

### Is this a regression?

No

### Description

the camelToKebab function is currently transforming the kebab cased string to a kebab case with multiple "-" characters.

Example:
camelToKebab("test-string") will return "test--string".

The function should do nothing to the kebab-cased string. The function should return "this-is-a-test-string" if we pass "ThisIsA-test-string"

### Please provide the MonsterJS package versions

```true
core: 1.4.33
cli: 1.4.33
```

**Comment by Aksa12** [comment]
Hey, I would like to work on this issue

**Comment by mfpjayb** [comment]
> Hey, I would like to work on this issue

Sure, thank you!
